### ISSUE TITLE
Unable to find type [System.IO.Compression.ZipFile

### ISSUE THREAD

**Issue by Dsrygaard** [AzureAD/AzureADAssessment#61] opened 2022-08-04 15:27 UTC
Getting this error: Unable to find type [System.IO.Compression.ZipFile

Dumps from PS:

Exporting UserReport: Completed 78,906 in 00:13:31
Loading groups in lookup cache
Exporting NotificationsEmailsReport: Completed 85 in 00:00:06
Loading administrative units in lookup cache
Loading applications in lookup cache
Loading service principals in lookup cache
Exporting RoleAssignmentReport: Completed 1,232 in 00:00:15
Exporting AppCredentialsReport: Completed 18,856 in 00:02:36
Exporting ConsentGrantReport: Completed 49,738 in 00:05:36
WARNING: The export package has not been generated
WARNING: If you are working with microsoft or a provider on the assessment please warn them
WARNING: Please check GitHub issues and fill a new one or reply on existing ones mentionning the errors seen
WARNING: https://github.com/AzureAD/AzureADAssessment/issues
Unable to find type [System.IO.Compression.ZipFile].

Any solution for this?

**Comment by padmavc** [comment] 2022-08-04 15:44
@Dsrygaard which version are you using? can you get latest version and try Install-Module -Name AzureADAssessment -AllowPrerelease

**Comment by Dsrygaard** [comment] 2022-08-06 13:05
Solved by adding Add-Type -AssemblyName System.IO.Compression.FileSystem before running the script

**Comment by jasoth** [comment] 2022-09-02 15:41
I found the cause for this. It was only happening on Windows PowerShell but has been fixed now.

**Closed by jasoth** 2022-09-02 15:41 UTC
